name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate Changelog
        uses: github-changelog-generator/github-changelog-generator@v1.16.3
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.generate_changelog.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
